### ISSUE TITLE
TypeError: 'ExtractResult' object is not subscriptable

### ISSUE THREAD

**Issue by lol1qazxsw2** [zongdeiqianxing/Autoscanner#27]
看样子oneforall是扫完了  后面出了问题  查报错是参数格式不对  没找到对应目录的代码
`rs.georgia.gov', 'www.forms.agr.georgia.gov', 'www.georgiadrivers.georgia.gov', 'betammis.georgia.gov', 'www.smeb.georgia.gov', 'ipas.otfs.georgia.gov', 'ocss.dhr.georgia.gov', 'sihome.gets.georgia.gov', 'www.open.georgia.gov', 'trauma.georgia.gov', 'www.ltgov.georgia.gov']

2024-08-16 16:07:43.150 | INFO     | lib.Tools:__init__:56 - www.georgia.gov - Oneforall - over
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    AutoScanner()
  File "main.py", line 24, in __init__
    controller.assign_task()
  File "/root/lib/controller.py", line 51, in assign_task
    if tldextract.extract(subdomain)[0]:       # 如果子域名部分为空就不扫了，因为肯定有www.形式的
TypeError: 'ExtractResult' object is not subscriptable
`

**Comment by lol1qazxsw2** [comment]
> 看样子oneforall是扫完了 后面出了问题 查报错是参数格式不对 没找到对应目录的代码 `rs.georgia.gov', 'www.forms.agr.georgia.gov', 'www.georgiadrivers.georgia.gov', 'betammis.georgia.gov', 'www.smeb.georgia.gov', 'ipas.otfs.georgia.gov', 'ocss.dhr.georgia.gov', 'sihome.gets.georgia.gov', 'www.open.georgia.gov', 'trauma.georgia.gov', 'www.ltgov.georgia.gov']
> 
> 2024-08-16 16:07:43.150 | INFO | lib.Tools:**init**:56 - [www.georgia.gov](http://www.georgia.gov) - Oneforall - over Traceback (most recent call last): File "main.py", line 28, in AutoScanner() File "main.py", line 24, in **init** controller.assign_task() File "/root/lib/controller.py", line 51, in assign_task if tldextract.extract(subdomain)[0]: # 如果子域名部分为空就不扫了，因为肯定有www.形式的 TypeError: 'ExtractResult' object is not subscriptable `

Autoscanner/lib/controller.py  line 51
 if subdomain[0]:
